server:
  port: 10005
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: shop
          uri: lb://shop
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=1 #转发时去掉shop
      discovery:
        locator:
          lower-case-service-id: true